//Check stage
LIST @HOL_DB.EXTERNAL.FROSTBYTE_RAW_STAGE;

//Check weather db
SELECT * FROM FROSTBYTE_WEATHERSOURCE.ONPOINT_ID.POSTAL_CODES LIMIT 100;

SELECT * FROM HOL_DB.HARMONIZED.POS_FLATTENED_V LIMIT 100;

//Execute the UDF in Snowflake
SELECT ANALYTICS.FAHRENHEIT_TO_CELSIUS_UDF(35);

//Running the Sproc in Snowflake
CALL HOL_DB.HARMONIZED.ORDERS_UPDATE_SP();
CALL HOL_DB.ANALYTICS.DAILY_CITY_METRICS_UPDATE_SP();
